scrape_configs:
  - job_name: 'promexample'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['myip:8080']
        labels:
          group: 'some-group'
